version: 0.2

env:
  variables:
    ENV: "stage"
    PYTHONPATH: "src"
    SAGEMAKER_JOB_NAME: "semantic-search-nlp-for-training"
    INPUT_S3_BUCKET: "webpresence-geocore-geojson-to-parquet"
    OUTPUT_S3_BUCKET: "webpresence-nlp-data-preprocessing"
    DATA_SPLIT_RATIO: "0.1"
    KEEP_EOCOLLECTIONS: "false"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies
      - python -m pip install --upgrade pip
      - pip install pytest pandas pyarrow

  pre_build:
    commands:
      - echo Environment is set to $ENV
      - echo Running tests from $PYTHONPATH
      - export INPUT_S3_BUCKET="${INPUT_S3_BUCKET}-${ENV}"
      - export OUTPUT_S3_BUCKET="${OUTPUT_S3_BUCKET}-${ENV}"
      - echo Starting pytest...
      - pytest

  build:
    commands:
      - python src/data_processing/preprocess_data.py

  post_build:
    commands:
      - echo Tests completed.

artifacts:
  type: NO_ARTIFACTS