name: Run UnitTests via Pytest

on:
  workflow_dispatch:
  

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas pyarrow
      - name: Run pytest
        run: |
          pytest
